"use client";

// Import the hooks we just created
import { useArticleById, useUpdateArticle } from "@/services/blog";

import ArticleForm from "@/components/article-form";
import { useToast } from "@/hooks/use-toast";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";

export default function AdminEditArticlePage() {
  const { id } = useParams() as { id: string };
  const router = useRouter();
  const { toast } = useToast();

  // 1. Fetch the specific article data
  const { data: articleResponse, isLoading, isError } = useArticleById(id);
  const article = articleResponse?.data;

  // 2. Setup the update mutation
  const { mutate: updateArticle, isPending } = useUpdateArticle();

  // --- LOADING STATE ---
  if (isLoading) {
    return (
      <div className="w-full space-y-6 animate-in fade-in duration-500 slide-in-from-bottom-4">
        <Skeleton className="h-10 w-32 rounded-md" />
        <div className="space-y-2">
          <Skeleton className="h-10 w-1/3 rounded-lg" />
          <Skeleton className="h-4 w-1/4 rounded-lg" />
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <Skeleton className="lg:col-span-2 h-150 w-full rounded-xl" />
          <Skeleton className="h-100 w-full rounded-xl" />
        </div>
      </div>
    );
  }

  // --- ERROR STATE ---
  if (isError || !article) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center animate-in fade-in duration-500">
        <h2 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
          Article Not Found
        </h2>
        <p className="text-slate-500 dark:text-slate-400 mt-2 mb-6">
          The article you are trying to edit does not exist or has been deleted.
        </p>
        <Button asChild>
          <Link href="/blog">Return to Articles</Link>
        </Button>
      </div>
    );
  }

  // --- SUCCESS RENDER ---
  return (
    <div className="w-full animate-in fade-in duration-500 slide-in-from-bottom-4">
      {/* Back Navigation */}
      <div className="mb-6 flex items-center gap-2">
        <Button
          asChild
          variant="ghost"
          size="sm"
          className="text-slate-500 hover:text-slate-900 dark:hover:text-slate-100 hover:bg-slate-100 dark:hover:bg-slate-800"
        >
          <Link href="/blog">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Articles
          </Link>
        </Button>
      </div>

      {/* Page Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
          Edit Article
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1 flex items-center gap-2">
          Editing:{" "}
          <span className="font-semibold text-slate-700 dark:text-slate-300">
            {article.title}
          </span>
        </p>
      </div>

      {/* Article Form Component */}
      <ArticleForm
        initialData={article}
        isSubmitting={isPending}
        onSubmit={(data) => {
          // data here is a FormData object generated by your ArticleForm component
          updateArticle(
            { id, data },
            {
              onSuccess: () => {
                toast({
                  variant: "success",
                  title: "Changes saved successfully!",
                });
                router.push("/blog");
              },
              onError: (error: any) => {
                toast({
                  variant: "destructive",
                  title: "Failed to save changes",
                  description:
                    error?.message || "An unexpected error occurred.",
                });
              },
            },
          );
        }}
      />
    </div>
  );
}
